#https://hub.docker.com/_/mysql
FROM mysql

# environment variable
ENV MYSQL_ROOT_PASSWORD Test123456

# commands docker

# see images
# docker image ls
# see containers
# docker ps

# make image
# docker build -t mysql-image-test -f api/db/Dockerfile .

# run image created previously
# docker run -d --rm --name mysql-container-test mysql-image-teste

# execute script
# docker exec -i mysql-container-test mysql -uroot -pTest123456 < api/db/script.sql

# enter in shell of the container
# docker exec -it mysql-container-test /bin/sh
